
disabled_rules:
 - vertical_whitespace
 - trailing_whitespace
 - colon
 - line_length
 - trailing_newline
 - unused_closure_parameter
 - comma
 - identifier_name
 - function_body_length
 
cyclomatic_complexity:
 ignores_case_statements: true
  
excluded:
 - Pods
